# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'CME 252'
tagline:          'Introduction to Optimization'
description:      'Introduction to Optimization'
url:              http://ajfriend.github.io/
baseurl:          /cme252

author:
  name:           'AJ Friend'

github:
  repo:           https://github.com/ajfriend/cme252